Importing the Dependencies

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [7]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [8]:
# first 5 rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [9]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [10]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [11]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [12]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This Dataset is highly unblanced

0 -> Normal Transaction

1 -> fraudulent transaction

In [13]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [14]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [15]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [16]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [17]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Building a sample dataset that contain similar distribution of normal transactions and fraudulent Transactions

Number of Fraudulent Transactions -> 492

In [18]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [19]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [20]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
68234,52892.0,-1.017883,0.254338,2.165488,2.647700,1.096038,0.004497,-0.294449,0.345965,-1.284601,...,0.178281,0.298411,0.239105,0.071747,-0.713274,-0.029045,0.162121,0.178472,0.77,0
187306,127476.0,1.707236,-0.227707,-1.583226,1.609597,0.091778,-1.327355,0.866316,-0.495653,0.128424,...,0.170895,0.385143,-0.086401,0.418480,0.353467,-0.531822,-0.041546,-0.031087,160.00,0
138194,82531.0,-0.895862,1.316846,1.421313,1.989045,0.197293,0.080033,0.327285,0.523607,-1.069240,...,-0.114342,-0.436893,-0.155257,-0.170199,0.041382,-0.103722,-0.027830,0.036039,9.49,0
236232,148723.0,-0.309891,1.143075,-0.351601,-0.294735,0.685605,-0.636571,0.821767,-0.183181,-0.132890,...,-0.162427,-0.400529,0.109896,-0.634142,-0.798220,-0.065344,-0.603579,-0.175132,2.50,0
71855,54468.0,-7.209847,5.682077,-2.547282,-2.312535,-2.844714,-0.936004,-1.911862,3.059635,2.730815,...,-0.433845,-0.446210,0.472967,-0.063761,0.583901,0.725577,0.587513,-0.075107,1.46,0

In [21]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [22]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [23]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95240.597561,0.018302,-0.001113,0.034649,-0.090624,-0.087808,-0.034407,-0.048849,0.032392,-0.021820,...,0.016099,0.021555,0.021322,-0.032288,0.055422,-0.006459,0.023745,0.006736,0.005235,87.547866
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features & Targets

In [24]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [25]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
68234    52892.0 -1.017883  0.254338  2.165488  2.647700  1.096038  0.004497
187306  127476.0  1.707236 -0.227707 -1.583226  1.609597  0.091778 -1.327355
138194   82531.0 -0.895862  1.316846  1.421313  1.989045  0.197293  0.080033
236232  148723.0 -0.309891  1.143075 -0.351601 -0.294735  0.685605 -0.636571
71855    54468.0 -7.209847  5.682077 -2.547282 -2.312535 -2.844714 -0.936004
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
68234  -0.294449  0.345965 -1.284601  ...  0.210478  0.178281  0.298411
187306  0.866316 -0.495653  0.128424  ...  0.004652  0.170895  0.385143
138194  0.327285  0.523607 -1.069240  ... -0.177803 -0.114342 -0.436893
236232  0.821767 -0.183181 -0.132890  ... -0.143882 -0.162427 -0.400529
71855  -1.911862  3.059635  2.730815  ...  1.836363 -0.433845 -0.446210
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
68234   0.239105  0.071747 -0.713274 -0.029045  0.162121  0.178472    0.77
187306 -0.086401  0.418480  0.353467 -0.531822 -0.041546 -0.031087  160.00
138194 -0.155257 -0.170199  0.041382 -0.103722 -0.027830  0.036039    9.49
236232  0.109896 -0.634142 -0.798220 -0.065344 -0.603579 -0.175132    2.50
71855   0.472967 -0.063761  0.583901  0.725577  0.587513 -0.075107    1.46
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [26]:
print(Y)

68234     0
187306    0
138194    0
236232    0
71855     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Split the data into Training data & Testing Data

In [45]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [46]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

Model Training

Logistic Regression

In [53]:


from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import numpy as np



target = Y_train


print("X_train shape:", X_train.shape)
print("Target shape before ravel:", np.array(target).shape)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)


target = np.ravel(target)

# Fit Logistic Regression
model = LogisticRegression(
    class_weight='balanced',
    solver='lbfgs',
    max_iter=5000,
    random_state=42
)
model.fit(X_train_scaled, target)

print("Converged in (per class):", model.n_iter_)

X_train shape: (787, 30)
Target shape before ravel: (787,)
Converged in (per class): [26]

Model Evaluation

Accuracy Score

In [58]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Predict
y_pred = model.predict(X_test_scaled)

# Evaluate
print("Accuracy:", accuracy_score(Y_test, y_pred))
print("\nClassification Report:\n", classification_report(Y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, y_pred))

Accuracy: 0.9137055837563451

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.95      0.92        99
           1       0.95      0.88      0.91        98

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197


Confusion Matrix:
 [[94  5]
 [12 86]]

Accuracy score on training data

In [59]:
# Predict on training data
y_train_pred = model.predict(X_train_scaled)

# Evaluate training performance
print("=== Training Performance ===")
print("Training Accuracy:", accuracy_score(Y_train, y_train_pred))
print("\nTraining Classification Report:\n", classification_report(Y_train, y_train_pred))
print("\nTraining Confusion Matrix:\n", confusion_matrix(Y_train, y_train_pred))

=== Training Performance ===
Training Accuracy: 0.9555273189326556

Training Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.98      0.96       393
           1       0.98      0.93      0.95       394

    accuracy                           0.96       787
   macro avg       0.96      0.96      0.96       787
weighted avg       0.96      0.96      0.96       787


Training Confusion Matrix:
 [[387   6]
 [ 29 365]]

Accuracy score on test data

In [60]:
# Predict on test data (already scaled)
y_test_pred = model.predict(X_test_scaled)

# Evaluate test performance
print("\n=== Test Performance ===")
print("Test Accuracy:", accuracy_score(Y_test, y_test_pred))
print("\nTest Classification Report:\n", classification_report(Y_test, y_test_pred))
print("\nTest Confusion Matrix:\n", confusion_matrix(Y_test, y_test_pred))

# Compare train vs test accuracy
print(f"\nTrain-Test Gap: {abs(accuracy_score(Y_train, y_train_pred) - accuracy_score(Y_test, y_test_pred)):.2f}")

=== Test Performance ===
Test Accuracy: 0.9137055837563451

Test Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.95      0.92        99
           1       0.95      0.88      0.91        98

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197


Test Confusion Matrix:
 [[94  5]
 [12 86]]

Train-Test Gap: 0.04